name: Deploy

on:
    push:
        branches:
            - main
        tags:
            - v*.*

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install pnpm
              id: pnpm-install
              uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Build website
              run: pnpm build
              env:
                  NODE_ENV: production
